<a href="https://colab.research.google.com/github/ayanand/CapstoneML/blob/main/analysiscap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/ayanand/CapstoneML/blob/main/analysiscap.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
</table>

In [ ]:
import pandas as pd
!pip install fsspec
!pip install gcsfs 
 
 


In [ ]:
df = pd.read_csv('gs://capstoragebucket2020/All_joined_v3.csv')

In [ ]:
df.tail()

latitude  longitude  ...  averagesizeofcensusfamilies  workers
30826     45.67     -73.52  ...                          3.1      515
30827     45.67     -73.52  ...                          3.1      515
30828     45.67     -73.52  ...                          3.1      515
30829     45.67     -73.52  ...                          3.1      515
30830     45.67     -73.52  ...                          3.1      515

[5 rows x 29 columns]

In [ ]:
df=df.sort_values(by=['year', 'month','latitude','longitude'])

In [ ]:
df['INCENDIE_count'].value_counts()

0    25197
1     4700
2      766
3      132
4       26
5        7
6        2
7        1
Name: INCENDIE_count, dtype: int64

In [ ]:
df_new.describe()

month          year  ...       workers      distance
count  30831.000000  30831.000000  ...  30831.000000  30831.000000
mean       6.381337      3.589472  ...    176.204470     24.675067
std        3.383709      1.673232  ...    147.235356     10.024351
min        1.000000      1.000000  ...      0.000000      0.000000
25%        3.000000      2.000000  ...    105.000000     17.000000
50%        6.000000      4.000000  ...    145.000000     25.000000
75%        9.000000      5.000000  ...    205.000000     32.000000
max       12.000000      6.000000  ...   1270.000000     50.000000

[8 rows x 26 columns]

In [ ]:
df_new = df
df_new['year'] =2021- df_new['year']

In [ ]:
import geopy.distance

def dist(x,y):
  coords_1 = (45.70, -73.47)
  coords_2 = (x, y)
  return geopy.distance.vincenty(coords_1, coords_2).km


In [ ]:
df_new['distance']=0

In [ ]:
for x in range(0,len(df_new)-1):
  df_new['distance'][x]=dist(df_new['latitude'][x], df_new['longitude'][x])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
df_new.tail(10)

latitude  longitude  ...  workers  distance
3490      45.66     -73.51  ...      135         5
3215      45.66     -73.50  ...      290         5
3531      45.66     -73.49  ...      110         4
30665     45.67     -73.55  ...       75         7
30708     45.67     -73.51  ...      165         4
30567     45.67     -73.50  ...      100         4
27222     45.68     -73.50  ...      335         3
23755     45.69     -73.50  ...      580         2
23850     45.69     -73.49  ...      195         1
19863     45.70     -73.49  ...      170         1

[10 rows x 30 columns]

In [ ]:

df_new = df_new.drop("latitude", axis=1)
df_new = df_new.drop("longitude", axis=1)

In [ ]:
df_new = df_new.drop("min_annee_construction", axis=1)
df_new = df_new.drop("max_annee_construction", axis=1)

In [ ]:
y= df_new["INCENDIE_count"].copy()
X=df_new.drop("INCENDIE_count", axis=1)

In [ ]:
len(X),len(y)

(30831, 30831)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

scaler = StandardScaler()
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X=scaler.transform(X)

In [ ]:
X

0         1         2   ...        22        23        24
0     -1.590392  1.440665 -0.737418  ...  0.287008 -0.177980  2.326865
1     -1.590392  1.440665 -0.432712  ...  0.287008 -0.177980  2.227106
2     -1.590392  1.440665 -0.128006  ...  0.287008 -0.177980  2.127348
3     -1.590392  1.440665 -0.128006  ...  0.455222 -0.381738  2.127348
4     -1.590392  1.440665 -0.432712  ...  0.455222 -0.449658  2.027589
...         ...       ...       ...  ...       ...       ...       ...
30826  1.069454 -1.547612 -0.737418  ... -0.385849 -0.517577 -2.062518
30827  1.069454 -1.547612 -0.737418  ... -0.217635  1.078532 -2.162277
30828  1.069454 -1.547612 -0.737418  ...  0.118794  2.742562 -2.262035
30829  1.069454 -1.547612 -0.737418  ... -0.217635  0.127658 -2.361794
30830  1.069454 -1.547612 -0.737418  ...  0.118794 -0.042140 -2.361794

[30831 rows x 25 columns]

In [ ]:
X=pd.DataFrame(X)

In [ ]:
corr_matrix = df_new.corr()
corr_matrix["INCENDIE_count"].sort_values(ascending=False)

INCENDIE_count                  1.000000
sum_nombre_logement             0.345779
sum_etage_hors_sol              0.296308
total_crimes                    0.282805
ALARMES_INCENDIES_count         0.277268
Introduction_count              0.249569
Mefait_count                    0.237519
Vol_moteur_count                0.186271
vols_count                      0.180177
caserne_count                   0.109855
sum_superficie_batiment         0.083279
Vol_de_vehicule_count           0.069761
dwellings                       0.055430
households                      0.035212
sum_superficie_terrain          0.031230
Infractions_entrainant_count    0.022128
month                          -0.010032
year                           -0.014955
population                     -0.023563
averageage                     -0.029906
workers                        -0.039661
averagesizeofcensusfamilies    -0.044341
distance                       -0.081604
averagehouseholdsize           -0.109993
area            

In [ ]:
y_test.value_counts()

0    4276
1     824
2     120
3      25
5       4
4       3
Name: INCENDIE_count, dtype: int64

In [ ]:
X_train=X[df_new['year'] > 2] # choose 2019 data as train
X_test =X[df_new['year'] == 2] # choose 2019 data as validation
y_train = y[df_new['year'] > 2]
y_test = y[df_new['year'] == 2]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


In [ ]:
#from sklearn.model_selection import train_test_split
#train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

len(X_train),len(X_test),len(y_train),len(y_test)

(21306, 5252, 21306, 5252)

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lin_reg.coef_

array([-0.00291858, -0.00172223,  0.00237662,  0.00021814,  0.00539962,
        0.00015952, -0.00462729,  0.0028058 , -0.00210421, -0.00232755,
       -0.005672  , -0.01165894,  0.00726919,  0.00331495, -0.00080201,
       -0.00141485, -0.00266147, -0.03655681, -0.0090073 ,  0.03375801,
        0.01574148, -0.00579018, -0.00715466,  0.01226602, -0.00629226])

In [ ]:
print(lin_reg.score(X_train, y_train))

0.0011305598898968539


In [ ]:

print(lin_reg.score(X_test,y_test))

-0.0023258242455788114


In [ ]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42,max_depth=5)
tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=5,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=42, splitter='best')

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

y_predictions = tree_reg.predict(X_test)
tree_mse = mean_squared_error(y_test, y_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.5208440063746566

In [ ]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(n_estimators=10, random_state=42, max_depth=10)
forest_reg.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=10, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [ ]:
print(str(forest_reg.score(X_train, y_train)) + " "+ str(forest_reg.score(X_test, y_test) ))

0.11930446396844786 -0.029478710497101934


In [ ]:
from sklearn.svm import SVR

svm_reg = SVR(kernel="linear")
svm_reg.fit(train_set_n, train_labels)
train_predictions = svm_reg.predict(train_set_n)
svm_mse = mean_squared_error(train_labels, train_predictions)
svm_rmse = np.sqrt(svm_mse)
svm_rmse

In [ ]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
# prepare the cross-validation procedure
cv = KFold(n_splits=5, random_state=1, shuffle=True)
# create model
xgboost = XGBClassifier()
# evaluate model
xgboost_scores = cross_val_score(xgboost, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (mean(xgboost_scores ), std(xgboost_scores )))

Accuracy: 0.820 (0.008)


In [ ]:

xgboost.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
y_test_pred = xgboost.predict(X_test)

In [ ]:

print('Accuracy of XGboost classifier on test set: {:.2f}'.format(xgboost.score(X_test, y_test)))

Accuracy of XGboost classifier on test set: 0.81


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix_valid = confusion_matrix(y_test, y_test_pred)
print(confusion_matrix_valid)

[[4276    0    0    0    0    0]
 [ 824    0    0    0    0    0]
 [ 120    0    0    0    0    0]
 [  25    0    0    0    0    0]
 [   3    0    0    0    0    0]
 [   4    0    0    0    0    0]]
